### ISSUE TITLE
app start failed

### ISSUE THREAD

**Issue by shengkaixuan** [abetlen/ggml-python#11]
followed the https://github.com/abetlen/ggml-python/tree/main/examples/replit example ,got the following error.
please tell me how to deal with it?
`(base) [test@rockytest replit]$  MODEL=/data/ggml-python/examples/replit/replit-code-v1-3b-q4_0.bin uvicorn app:app --reload --host 0.0.0.0
INFO:     Will watch for changes in these directories: ['/data/ggml-python/examples/replit']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [61255] using StatReload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/home/test/miniconda3/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/test/miniconda3/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/test/miniconda3/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/test/miniconda3/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/test/miniconda3/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/test/miniconda3/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/test/miniconda3/lib/python3.10/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/test/miniconda3/lib/python3.10/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/test/miniconda3/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/home/test/miniconda3/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/data/ggml-python/examples/replit/app.py", line 533, in <module>
    settings = Settings()  # type: ignore
  File "pydantic/env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Settings
model_file
  field required (type=value_error.missing)`

**Comment by laurids-reichardt** [comment]
You need to provide `Settings` with the path to your ggml model inside `app.py` at the following line: https://github.com/abetlen/ggml-python/blob/c4cb698cd2068addafe0b2b4fd3c63b49061f5c8/examples/replit/app.py#L533
